<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class positionSeeder extends Seeder
{
    public function run()
    {
        DB::table('positions')->insert([
            [
                'title' => 'Physician/Doctor',
                'description' => 'A licensed medical professional responsible for diagnosing and treating patients.',
                'salary' => 120000.00,
                'department' => 'Medical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Resident/Intern',
                'description' => 'Medical graduates in training under supervision to become licensed physicians.',
                'salary' => 60000.00,
                'department' => 'Medical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Registered Nurse',
                'description' => 'A licensed nurse who provides patient care, administers medication, and supports doctors.',
                'salary' => 75000.00,
                'department' => 'Nursing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Nurse Practitioner',
                'description' => 'A registered nurse with advanced training who can diagnose and treat illnesses.',
                'salary' => 95000.00,
                'department' => 'Nursing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Licensed Practical Nurse',
                'description' => 'A nurse who provides basic medical care and assists registered nurses.',
                'salary' => 50000.00,
                'department' => 'Nursing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Physician Assistant',
                'description' => 'A licensed professional who works under a physician to provide care to patients.',
                'salary' => 90000.00,
                'department' => 'Medical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pharmacist',
                'description' => 'A healthcare professional who prepares and dispenses medications to patients.',
                'salary' => 95000.00,
                'department' => 'Pharmacy',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Clinical Nurse Educator',
                'description' => 'A nurse responsible for teaching and training nursing staff.',
                'salary' => 80000.00,
                'department' => 'Nursing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Occupational Therapist',
                'description' => 'A healthcare professional who helps patients improve their ability to perform daily activities.',
                'salary' => 70000.00,
                'department' => 'Rehabilitation',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Physical Therapist',
                'description' => 'A healthcare professional who helps patients improve their movement and manage pain.',
                'salary' => 75000.00,
                'department' => 'Rehabilitation',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Speech-Language Pathologist',
                'description' => 'A professional who assesses and treats speech, language, and communication disorders.',
                'salary' => 70000.00,
                'department' => 'Rehabilitation',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Respiratory Therapist',
                'description' => 'A healthcare professional who provides care for patients with breathing difficulties.',
                'salary' => 65000.00,
                'department' => 'Respiratory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dietitian/Nutritionist',
                'description' => 'A professional who advises on proper eating habits for health and wellness.',
                'salary' => 60000.00,
                'department' => 'Nutrition',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mental Health Counselor',
                'description' => 'A professional who provides therapy to patients dealing with mental health issues.',
                'salary' => 70000.00,
                'department' => 'Mental Health',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Social Worker',
                'description' => 'A professional who helps patients cope with social, emotional, and financial challenges.',
                'salary' => 60000.00,
                'department' => 'Social Services',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Laboratory Technician',
                'description' => 'A professional who conducts tests and analyzes samples for medical diagnosis.',
                'salary' => 60000.00,
                'department' => 'Laboratory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hospital Administrator',
                'description' => 'Oversees hospital operations, budget, and staff.',
                'salary' => 110000.00,
                'department' => 'Administration',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Human Resources Manager',
                'description' => 'Responsible for managing employee relations, recruitment, and training.',
                'salary' => 80000.00,
                'department' => 'Human Resources',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Billing Specialist',
                'description' => 'Manages patient billing and insurance claims.',
                'salary' => 50000.00,
                'department' => 'Billing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Medical Records Clerk',
                'description' => 'Responsible for organizing and maintaining patient health records.',
                'salary' => 40000.00,
                'department' => 'Health Information Management',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Admissions Clerk',
                'description' => 'Processes patient admissions and maintains records.',
                'salary' => 35000.00,
                'department' => 'Admissions',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Receptionist',
                'description' => 'Greets visitors and manages front desk operations.',
                'salary' => 35000.00,
                'department' => 'Administration',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ward Clerk/Unit Secretary',
                'description' => 'Provides administrative support in patient care units.',
                'salary' => 40000.00,
                'department' => 'Nursing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Medical Transcriptionist',
                'description' => 'Transcribes medical reports and documents from audio recordings.',
                'salary' => 45000.00,
                'department' => 'Health Information Management',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Patient Coordinator',
                'description' => 'Assists patients in navigating healthcare services and appointments.',
                'salary' => 50000.00,
                'department' => 'Patient Services',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Compliance Officer',
                'description' => 'Ensures the hospital adheres to regulations and standards.',
                'salary' => 70000.00,
                'department' => 'Compliance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Data Analyst',
                'description' => 'Analyzes healthcare data to improve operations and patient outcomes.',
                'salary' => 75000.00,
                'department' => 'Analytics',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'IT Support Specialist',
                'description' => 'Provides technical support and maintains hospital IT systems.',
                'salary' => 60000.00,
                'department' => 'IT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Radiology Technician',
                'description' => 'Operates imaging equipment to help diagnose patient conditions.',
                'salary' => 65000.00,
                'department' => 'Radiology',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Phlebotomist',
                'description' => 'Draws blood for tests, transfusions, research, or blood donations.',
                'salary' => 40000.00,
                'department' => 'Laboratory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Certified Nursing Assistant (CNA)',
                'description' => 'Assists nurses and provides basic patient care.',
                'salary' => 35000.00,
                'department' => 'Nursing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Emergency Medical Technician (EMT)',
                'description' => 'Provides emergency medical care and transportation.',
                'salary' => 45000.00,
                'department' => 'Emergency Services',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Paramedic',
                'description' => 'Provides advanced emergency medical care and transportation.',
                'salary' => 55000.00,
                'department' => 'Emergency Services',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Surgical Technologist',
                'description' => 'Assists in surgical operations by preparing and maintaining the operating room.',
                'salary' => 50000.00,
                'department' => 'Surgery',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Orderly',
                'description' => 'Assists in the transport of patients and ensures patient safety.',
                'salary' => 30000.00,
                'department' => 'Nursing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Patient Transporter',
                'description' => 'Transports patients to various departments within the hospital.',
                'salary' => 32000.00,
                'department' => 'Transport',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
